version: '3.7'
services:
    redis:
        restart: unless-stopped
        image: "redis:alpine"
        expose: 
            - "6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
    socket:
        restart: unless-stopped
        # the path of directory for build
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env.local
        # the changes in my local will be reflected into container (development only)
        volumes:
            - .:/usr/src/app
            # - /usr/src/app/node_modules
        ports:
            - "8080:8080"
        expose: # internal ports
            - "8080"
        environment:
            NODE_ENV: development
            SERVER_PORT: 8080
            REDIS_HOST: "redis"
        links:
            - "redis"
        depends_on:
            redis:
                condition: service_healthy
# docker-compose up -d --no-deps --build --no-cache <service_name>