version: '3.7'
services:
    redis:
        image: "redis:alpine"
        expose: 
            - "6379"
        deploy:
            replicas: 1
            # how the service should be rollback if failing updates
            rollback_config: 
                # all container rollback simultanenously
                parallelism: 0  
            update_config: 
                # number of container rollback in a single time. 
                parallelism: 1 
            restart_policy:
                condition: on-failure
                # duration required for restart attempts
                delay: 10s 
                # maximum amount of attempts
                max_attempts: 3 
            resources:
                limits:
                    # 50% of single core
                    cpus: "0.5"
                    # 50M (Megabytes) of memory
                    memory: 50M
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
    socket:
        # the path of directory for build
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file: .env.local
        ports:
            - "8000:8000"
        expose: # internal ports
            - "8000"
        environment:
            NODE_ENV: production
            SERVER_PORT: 8000
            REDIS_HOST: "redis"
        image: "digital-signal-processing-exercises"
        links:
            - "redis"
        deploy:
            mode: global
        depends_on:
            redis:
                condition: service_healthy
# docker-compose up -d --no-deps --build --no-cache <service_name>